### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by aminya** [saeedeh/google-books-download#2]
I get the following error when trying in Firefox nightly:
```
TypeError: scrollBar is nulldebugger eval code:25:1
    <anonymous> debugger eval code:25
```
And this:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/play/log?format=json. (Reason: CORS header “Access-Control-Allow-Origin” missing).
```

After entering `finish()`:
```
ReferenceError: JSZip is not defineddebugger eval code:53:14
    finish debugger eval code:53
    <anonymous> debugger eval code:1
```

And in Chrome:
```
VM77:24 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at <anonymous>:24:11
(anonymous) @ VM77:24
books.googleusercontent.com/books/reader?id=kRoxDwAAQBAJ&printsec=frontcover&pg=GBS.PA86&guctk=14858622074141591420.1c5e5298a0dcf65d.1562787258.v1.ACfU3U06PLNYiz8iJEsdEesSjdBDgcppNQ&hl=en#?peer=https%253A%252F%252Fplay.google.com:1 Access to XMLHttpRequest at 'https://play.google.com/play/log?format=json' from origin 'https://books.googleusercontent.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
After entering `finish()`:
```
VM77:52 Uncaught ReferenceError: JSZip is not defined
    at finish (<anonymous>:52:14)
    at <anonymous>:1:1
```

Although, I tried this with one of my library's books (not free ones), so that could be the issue.

**Comment by saeedeh** [comment]
It works only when the page layout is the regular Google books preview like this:
![image](https://user-images.githubusercontent.com/5148337/61003918-dd6b4d80-a332-11e9-9c17-ed7fe066d081.png)
Is your book in this layout? In your Google library, you should choose 'preview book' (instead of 'read book') to see it in the above layout.

**Comment by aminya** [comment]
> 
> 
> It works only when the page layout is the regular Google books preview like this:
> Is your book in this layout? In your Google library, you should choose 'preview book' (instead of 'read book') to see it in the above layout.

Oh right. Readme didn't say that I should preview the book instead. For purchased ones, there is no preview option. 

Should I wait for the pages to get loaded or I can scroll fast?

**Comment by saeedeh** [comment]
> Should I wait for the pages to get loaded or I can scroll fast?
Wait to get loaded.

**Comment by saeedeh** [comment]
> Should I wait for the pages to get loaded or I can scroll fast?

Wait to get loaded.
